# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.7.0-browsers
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: sleep 5
      - run: yarn test
      - persist_to_workspace:
          root: .
          paths:
            - .
  release:
    docker:
      - image: circleci/node:10.7.0-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace: # workspaceをアタッチする
          at: .
      - run: yarn install
      - run: node_modules/vsce/out/vsce publish -p $PERSONAL_ACCESS_TOKEN --yarn
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
